import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import './AnswerVisualization.css';

export type ChartKind = 'production_trend' | 'health_review' | 'heat_conditions' | null;

const julyProduction = [{ day: '01 Jul', actual: 638, expected: 642 }, { day: '05 Jul', actual: 635, expected: 643 }, { day: '10 Jul', actual: 629, expected: 642 }, { day: '15 Jul', actual: 626, expected: 641 }, { day: '20 Jul', actual: 619, expected: 640 }, { day: '25 Jul', actual: 615, expected: 640 }, { day: '30 Jul', actual: 612, expected: 639 }];
const healthReview = [{ signal: 'Feed intake', status: 78 }, { signal: 'Movement', status: 82 }, { signal: 'Water intake', status: 75 }, { signal: 'Comfort', status: 80 }];
const heatConditions = [{ hour: '08:00', thi: 70 }, { hour: '10:00', thi: 74 }, { hour: '12:00', thi: 78 }, { hour: '14:00', thi: 82 }, { hour: '16:00', thi: 80 }, { hour: '18:00', thi: 75 }];

export function AnswerVisualization({ kind }: { kind: ChartKind }) {
  if (!kind) return null;
  if (kind === 'production_trend') return <section className="answer-chart" aria-label="July milk production trend chart"><div><p className="panel-label">INTERACTIVE VISUAL</p><h4>July milk production trend</h4><p>Hover over a point to compare the observed daily total with the expected range.</p></div><ResponsiveContainer width="100%" height={270}><LineChart data={julyProduction} margin={{ top: 12, right: 20, left: 0, bottom: 4 }}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="day" /><YAxis unit=" L" width={58} /><Tooltip /><Legend /><Line type="monotone" dataKey="actual" name="Observed production" stroke="#2f6fb0" strokeWidth={3} activeDot={{ r: 6 }} /><Line type="monotone" dataKey="expected" name="Expected production" stroke="#5a9d74" strokeDasharray="5 4" strokeWidth={2} /></LineChart></ResponsiveContainer></section>;
  if (kind === 'health_review') return <section className="answer-chart" aria-label="Cow health observation chart"><div><p className="panel-label">INTERACTIVE VISUAL</p><h4>Health observation review</h4><p>Hover over each observation to review the current check status for the selected cow.</p></div><ResponsiveContainer width="100%" height={270}><BarChart data={healthReview} margin={{ top: 12, right: 20, left: 0, bottom: 4 }}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="signal" /><YAxis domain={[0, 100]} unit="%" width={48} /><Tooltip /><Bar dataKey="status" name="Observation status" fill="#4c9a70" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></section>;
  return <section className="answer-chart" aria-label="Heat conditions chart"><div><p className="panel-label">INTERACTIVE VISUAL</p><h4>Daily heat-load pattern</h4><p>Hover over the chart to review the estimated comfort conditions through the day.</p></div><ResponsiveContainer width="100%" height={270}><LineChart data={heatConditions} margin={{ top: 12, right: 20, left: 0, bottom: 4 }}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="hour" /><YAxis domain={[65, 85]} /><Tooltip /><Line type="monotone" dataKey="thi" name="Heat-load index" stroke="#d78a32" strokeWidth={3} activeDot={{ r: 6 }} /></LineChart></ResponsiveContainer></section>;
}
